export const DECIDUOUS_PHENOTYPE = Object.freeze({
  name: 'open-crown deciduous',
  width: 96,
  height: 128,
  groundY: 120,
  crown: Object.freeze({
    centerX: 48,
    centerY: 58,
    radiusX: 38,
    radiusY: 48,
    radiusZ: 32
  }),
  cameraYaw: 0.2,
  perspectiveStrength: 0.07,
  growthEnvelopeOverscan: 1.04,
  attractionPointCount: 180,
  attractionGap: 0.1,
  architecture: Object.freeze({
    branchStartHeight: Object.freeze([22, 38]),
    trunkBaseRadius: Object.freeze([3.1, 4.1]),
    trunkTaper: Object.freeze([0.72, 1.32]),
    trunkLeanAngle: Object.freeze([0.025, 0.085]),
    trunkLeanAzimuth: Object.freeze([0, Math.PI * 2]),
    splitTrunkProbability: 0.65,
    splitTrunkHeight: Object.freeze([32, 46]),
    splitTrunkAngle: Object.freeze([0.3, 0.4]),
    splitTrunkAzimuth: Object.freeze([0, Math.PI * 2])
  }),
  trunkTopY: 43,
  primaryBranchCount: 5,
  primaryBranchAngle: 0.88,
  internodeLength: 3.4,
  influenceRadius: 25,
  killRadius: 4.2,
  maxIterations: 72,
  maxNodes: 420,
  maxGeneration: 4,
  apicalDominance: 0.23,
  parentDirectionWeight: 0.34,
  maximumTurnAngle: 0.3,
  maximumAxisDeviation: 0.82,
  lowerBranchFloorY: 66,
  lowerBranchTransitionHeight: 14,
  lowerBranchMaximumDroop: 0.12,
  phototropism: 0.18,
  forkProbability: 0.3,
  minimumForkPoints: 7,
  forkSeparation: 0.28,
  minimumVigor: 0.08,
  vigorDecay: 0.965,
  terminalRadius: 0.55,
  pipeExponent: 2.15,
  foliageMinimumOrder: 2,
  foliageTerminalCoverage: 1,
  foliageCoverageColumns: 6,
  foliageCoverageRows: 7,
  foliageCoverageSamples: 3,
  foliageMinimumCellCoverage: 0.34,
  foliageMaximumTopUpCells: 10,
  foliageTopUpSupportsPerCell: 3,
  foliageSupplementalLeafCount: Object.freeze([8, 12]),
  foliageSupportRadius: 18,
  foliageMinimumLeafSpacing: 1.2,
  terminalLeafCount: Object.freeze([10, 16]),
  highOrderLeafCount: Object.freeze([5, 9]),
  secondaryLeafCount: Object.freeze([2, 5]),
  secondaryShootProbability: 0.42,
  leafRadiusX: Object.freeze([1.75, 2.6]),
  leafRadiusY: Object.freeze([2.65, 4]),
  leafShootSpread: Object.freeze([4, 8.5]),
  rootFlareHeight: 11,
  rootFlareStrength: 3.8
});
