export const FOREST_AUTHORED_RETENTION_DAYS = 90;
export const FOREST_AUTHORED_TOMBSTONE_RETENTION_MS = (
  FOREST_AUTHORED_RETENTION_DAYS * 24 * 60 * 60 * 1_000
);
export const FOREST_AUTHORED_RESET_RETENTION_MS = FOREST_AUTHORED_TOMBSTONE_RETENTION_MS;
