export const QUEST_ERROR_CODES = Object.freeze({
  NOT_FOUND: 'QUEST_NOT_FOUND',
  NOT_ACCEPTING_SUBMISSIONS: 'QUEST_NOT_ACCEPTING_SUBMISSIONS',
  ARCHIVED: 'QUEST_ARCHIVED',
  TYPE_MISMATCH: 'QUEST_TYPE_MISMATCH',
  ITEM_NOT_FOUND: 'QUEST_ITEM_NOT_FOUND',
  ITEM_UNAVAILABLE: 'QUEST_ITEM_UNAVAILABLE',
  CLAIM_EXPIRED: 'QUEST_CLAIM_EXPIRED',
  SUBMISSION_NOT_FOUND: 'QUEST_SUBMISSION_NOT_FOUND',
  SUBMISSION_INVALID_STATE: 'QUEST_SUBMISSION_INVALID_STATE',
  SUBMISSION_BLOCK_INELIGIBLE: 'QUEST_SUBMISSION_BLOCK_INELIGIBLE',
  SUBMISSION_BLOCK_CHANGED: 'QUEST_SUBMISSION_BLOCK_CHANGED',
  SUBMISSION_DUPLICATE: 'QUEST_SUBMISSION_DUPLICATE',
  REVIEW_COMMENT_REQUIRED: 'QUEST_REVIEW_COMMENT_REQUIRED',
  FORBIDDEN: 'QUEST_FORBIDDEN',
  INVALID: 'QUEST_INVALID'
});

export class QuestDomainError extends Error {
  constructor(code, { status = 400, details = null } = {}) {
    super(code);
    this.name = 'QuestDomainError';
    this.code = code;
    this.status = status;
    this.details = details;
  }
}

export function questError(code, options) {
  return new QuestDomainError(code, options);
}
